version: "3.8"

services:
  app:
    container_name: wastewise
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:4000"
    restart: on-failure
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "32769:3306"